### ISSUE TITLE
PyTorch installation may be too old

### ISSUE THREAD

**Issue by mahuahuahua** [divelab/MoleculeX#10]
Hello, I followed the instructions you provided for setting up the **AdvProp/graph** environment and successfully executed Step 1 'bash ./scripts/train_data.sh' and Step 2 'bash ./scripts/predict.sh'. Below are the details of each step. In Step 1, the file 'qm8.pt' was generated, indicating that this step was executed correctly. **However, I encountered an issue in Step 2: it displayed a message 'PyTorch installation may be too old',** despite the fact that the installation version of PyTorch (1.4.0) is explicitly specified in the YAML file. Could you please provide guidance on how to address this problem? Your prompt assistance would be greatly appreciated

**Comment by mahuahuahua** [comment]
Loading trained medel and testing...
Traceback (most recent call last):
  File "../src/predict.py", line 162, in <module>
    model.load_state_dict(torch.load(model_dir))
  File "/public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))                                        
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f35156d3193 in /public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f3517823f8b in /public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f35178251a4 in /public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x68ea06 (0x7f3524ce8a06 in /public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2701f4 (0x7f35248ca1f4 in /public/software/Miniconda37/envs/graph/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #29: __libc_start_main + 0xf5 (0x7f365cc55555 in /lib64/libc.so.6)
